spring:
  datasource:
    url: jdbc:mysql://localhost:3306/watering_backend_development
    username: watering_development_user
    password: ${DATABASE_PASSWORD}

authentication:
  access-token:
    iss: develop.watering.work
    aud:
      - discordbot.watering.work
    exp: 30
  refresh-token:
    exp: 15

aws:
  parameter-store:
    jwt:
      public-key: /develop/jwt/public_key
      private-key: /develop/jwt/private_key
