spring:
  datasource:
    url: jdbc:mysql://localhost:3306/watering_backend_development
    username: watering_staging_user
    password: ${DATABASE_PASSWORD}

authentication:
  access-token:
    iss: staging.watering.work
    aud:
      - discordbot.watering.work
    exp: 3600
  refresh-token:
    exp: 86400

aws:
  parameter-store:
    jwt:
      public-key: /staging/jwt/public_key
      private-key: /staging/jwt/private_key
