spring:
  datasource:
    url: jdbc:mysql://localhost:3306/watering_backend_development
    username: watering_staging_user
    password: ${DATABASE_PASSWORD}

authentication:
  access-token:
    iss: staging.watering.work
    aud:
      - discordbot.watering.work
    exp: 3600
  refresh-token:
    exp: 86400

aws:
  parameter-store:
    jwt:
      public-key: /staging/jwt/public_key
      private-key: /staging/jwt/private_key
  sqs:
    wait-time-seconds: 20
    max-number-of-messages: 10
    queues:
      watering-history: https://sqs.ap-northeast-1.amazonaws.com/417172458195/watering_staging_watering_histories
      temperature-history: https://sqs.ap-northeast-1.amazonaws.com/417172458195/watering_staging_temperature_histories
      humidity-history: https://sqs.ap-northeast-1.amazonaws.com/417172458195/watering_staging_humidity_histories
