spring:
  datasource:
    url: jdbc:mysql://localhost:3306/watering_backend_development
    username: watering_production_user
    password: ${DATABASE_PASSWORD}

authentication:
  access-token:
    iss: backend.watering.work
    aud:
      - discordbot.watering.work
    exp: 300
  refresh-token:
    exp: 3600

aws:
  parameter-store:
    jwt:
      public-key: /production/jwt/public_key
      private-key: /production/jwt/private_key
  sqs:
    wait-time-seconds: 20
    max-number-of-messages: 10
    queues:
      watering-history: https://sqs.ap-northeast-1.amazonaws.com/417172458195/watering_production_watering_histories
      temperature-history: https://sqs.ap-northeast-1.amazonaws.com/417172458195/watering_production_temperature_histories
      humidity-history: https://sqs.ap-northeast-1.amazonaws.com/417172458195/watering_production_humidity_histories
